import os
import discord
from discord.ext import commands
import random
import json
import math

# info on skills

# info on adult vs student

# info on learning skills and leveling up

# info on what numbers mean

# info on what credit rating translates to

def info_arche(archetype):

    match archetype:
        case "adventurer":
            msg = "A life without adventure is not worth living. The world is a big place and there is much to experience and many chances for glory. Sitting behind a desk, working a job nine to five is a death sentence for such folk. The adventurer years for excitement, fun, and a challenge. \nExamples: Bill Weasley, Sirius Black. \nAssociated skills: Apparition, Survival, Stealth, Cultural knowledge, First aid, Duelling (defence), Dodge, Charms, Quidditch."
        case "beefcake": 
            msg = "Physical, muscular, and capable of handling themselves when the chips are down. Born that way or has worked hard in the pursuit of physical perfection. You won't find these guys and gals in the library, but you might see their faces on a billboard. Beefcakes come in two varieties: the caring, silent type, or the brazen loud-mouth. \nExamples: Dudley (book 5 onwards), Crabbe and Goyle, Hagrid, Victor Krum. \nAssociated skills: Brawling, Psychology, Intimidate, Quidditch, Herbology, duelling (offence), dada, comc, flying (brooms)"
        case "bon vivant":
            msg = "A bon vivant is \"one who lives well\", but that doesn't neccesarily mean they are rich. While many are accustomed to wealth, the bon vivant is someone who could be said to enjoy life to the fullest and damn the consequences! Why wait until tomorrow when you can start living today? Enjoying food and drink, as well as other pleasurable pursuits, is the key to a lifestyle where excess is the norm. Whether poor or rich, such a person puts little thought to saving for a rainy day, preferring to be the center of attention and a friend to all. \nExamples: Horace Slughorn. \nAssociated skills: Arts/Crafts(any), Charm, Fast talk, Psychology, Language (other), Charms, Disguise, Apparition, Flying (brooms)"
        case "cold blooded":
            msg = "A rationalist who is capable of just about anything. Cold blooded types may follow some twisted moral code, however, their view of humanity is cold and stark; you're either good or bad. There are no shades of gray to navigate, just the harsh realities of life and death. Such people make effective killers as they have little self-doubt; they are ready to follow orders to the letter, or pursue some personal agenda for revenge. Such people may do anything to get the job done. They are rarely spontaneous people; instead, they embody ruthlessness and premeditation. Sometimes they will try to fool themselves into believing they have a \"line\" they will not cross, when in reality they are merciless and will go to any length to fullfill what they see is their goal. \nExamples: Barty Crouch Sr., Odysseus. \nAssociated skills: Disguise, Duelling (offence and defence), first aid, history of magic, intimidate, magical law, psychology, stealth, survival"
        case "dreamer":
            msg = "Whether an idealist or visionary, the dreamer has a strong and powerful mind. Such types tend to follow their own direction in life. The dreamer looks beyond the mundane realities of life, perhaps as a form of escapism or because they yearn for \"what could be,\" wishing to right wrongs or improve the world around them. \nExamples: Dumbledore \nAssociated skills: Arts/craft (any), Charm, History of magic, language (other), herbology, charms, divination, enchanting."
        case "egghead":
            msg = "Everything can be broken down and analysed in order to understand how it works. Knowledge is a treasure and a joy - a puzzle to explore. Where the scholar is bookish, the egghead is practical and thoroughly enjoys getting their hands dirty. Whether it's wires and gears, valves and computational engines, or blood and bones, the egghead likes to figure out what makes things tick. Perhaps an absent-minded genius or a razor-sharp virtuoso, the egghead can easily become absorbed in the problem before them, leaving them exposed and unaware of what is actually happening around them. \nExamples: Arthur Weasley (on muggles/technology) \nAssociated skills: Cultural knowledge, language (other), transfigurations, potions, astronomy, enchanting, alchemy, herbology"
        case "explorer":
            msg = "\"Don't fence me in,\" is the oft-heard cry of the explorer, who wishes for a more authentic and fullfilling life. Strong willed, virtually unshakeable, the explorer is ever questing for what lies over the horizon. Possibly at one with nature, such types are content to sleep where they fall, happily disdaining the soft comforts of urban life. Whether hacking through jungles, squeezing through caverns or simply charting the hidden quarters of the city, the explorer is often a misfit who grows up restless and annoyed by those they consider to be \"weak\" or \"cowards.\"\nExamples: Newt Scamander \n Associated skills: Care of magical creatures, cultural knowledge, brawling, first aid, language (other), magizoology, flying (brooms and creatures), stealth, herbology."
        case "le fatale":
            msg = "A deadly woman or man whose outward beauty usually masks a self-centered approach to life; one who is ever vigilant. By constructing an alluring and glamorous persona, the femme fatale is akin to a spider. She draws others to her web in order to possess what she desires or destroy her target. Brave and cunning, the femme fatale is not shy of getting her hands dirty and is a capable foe. Neither is she foolhardy, and she will wait until her web is constructed before dealing out a sudden and well-timed assault (be it mental or physical). A classic pulp archetype, the femme fatale could as easily be termed homme fatale if so desired.\nExamples: Veela, Cersei Lannister \nAssociated skills: acting, charm, disguise, flying (brooms), fast talk, brawling, duelling (offence), psychology, stealth, potions"
        case "grease monkey":
            msg = "The grease monkey is practically minded, able to make and repair all manner of things, be they useful inventions, machines, engines, or other devices. Grease Monkeys may be found lurking under the hood of a car, or playing with the telephone exchange wires. Such types have a \"can do\" attitude, able to make the most of what they have at hand, using their skills and experience to wow those around them. The grease monkey may be able to \"jury-rig\" all manner of gizmos, useful or otherwise.\nExamples: Rocket (guardians of the galaxy) \nAssociated skills: arts/craft (any), brawling, flying (brooms), exploding snap, muggle studies, enchanting, wandless magic, astronomy, potions"
        case "hard boiled":
            msg = "Tough and streetwise, someone who is hard boiled understands that to catch a thief you have to think like a thief. Usually, such a person isn\'t above breaking the law in order to get the job done. They\'ll use whatever tools are at their disposal and may crack a few skulls in the process. Often, at their core, they are honest souls who oppose that which wasn\'t so despicable and downright nasty; however, in order to fight for justice, they can be just as nasty as they need to be.\nExamples: Alastor Moody \nAssociated skills: brawling, duelling (offence), flying (brooms), fast talk, intimate, magical law, curse breaking, transfigurations, survival"
        case "harlequin":
            msg = "While similar to the femme fatale, the harlequin does not like to get their hands dirty (if they can help it). Usually possessing a magnetic personality, although not necessarily classically beautiful, such types find enjoyment in manipulating others to do their bidding, and often hide their own agendas behind outright lies or subtle deceptions. Sometimes they are committed to a cause (personal or otherwise), or act like agents of chaos, delighting in watching how people react to the situations they construe.\nExamples: Dolores Umbridge \nAssociated skills: acting, charm, disguise, fast talk, persuade, psychology, stealth, wizard chess"
        case "hunter":
            msg = "Maybe it's the thrill of the chase, the prize at the end, or just because they have an innate drive to master their environment, the hunter is relentless in pursuing their prey. Calm and calculated, the hunter is willing to track down his or her quarry for days, despising the reckless behavior of the unwary.\nExamples: Severus Snape (personality wise) \nAssociated skills: comc, duelling (both), first aid, magizoology, stealth, survival, potions, herbology"
        case "mystic":
            msg = "A seeker of the hidden, explorer of the unseen realm; the mystic quests for secrets and the fundamental truth of existence. They may be book-learned academics, shamanistic healers, circus diviners, or visionaries, but all pursue knowledge and the experience of forces outside of the natural order, be it for personal gain or the betterment of mankind. With the Keeper\'s permission, a mystic is able to tap into supernatural powers beyond the ken of average folk. Often they have been persecuted and hunted, hiding their \"gifts\" from those who would call them \"witch,\" while others are considered charlatans and little more than sideshow freaks. \nExamples: Trelawney, unspeakables \nAssociated skills: astronomy, disguise, hom, magiczoology, psychology, stealth, divination, arithmancy "
        case "outsider":
            msg = "The outsider stands apart from the rest of society, either figuratively or literally. Such people may be alien to the environment in which they find themselves, perhaps from a different country or culture, or they are part of the society but find themselves at odds with it. The outsider is usually on some form of journey, physically or spiritually, and must complete their objective before they can return to, or at last feel part of, the greater whole. Often the outsider will have distinct skills or a different way of approaching things; utilizing forgotten, secret, or alien knowledge.\nExamples: Flich, Myrtle, Firenze \nAssociated skills: arts/craft (any), comc, duelling (defence), first aid, intimidate, language (other), specialty healing, stealth, survival"
        case "rogue":
            msg = "The rogue disobeys rules of society, openly questioning the status quo and mocking those in authority. They delight in being non-conformists, acting on impulse and deriding conventional behavior. Laws are there to be broken or skirted around. Most rogues are not necessarily criminals or anarchists intent on spreading chaos, but rather they find amusement in pulling off stunts that will confound others. They are often sophisticated, governed by their own unique moral codes, loveable and careless.\nExamples: Fred & George \nAssociated skills: arts/crafts (any), charm, disguise, fast talk, magical law, psychology, stealth, transfigurations, charms"
        case "scholar":
            msg = "Uses intelligence and analysis to understand the world around them. Normally quite happy sitting in the library with a book (rather than actually facing the realities of life). A seeker of knowledge, the scholar is not particularly action orientated; however, when it comes to the crunch, he or she might be the only person who knows what to do.\" \nExamples: Hermione \nAssociated skills: Most hogwarts classes, magizoology, magical law, specialty healing, wizard chess and magical theory."
        case "seeker":
            msg = "Puzzles and riddles enthrall the seeker, who uses intelligence and reasoning to uncover mysteries and solve problems. They look for and enjoy mental challenges, always focused on finding the truth, no matter the consequences or tribulations they must face.\nExamples: Luna Lovegood \nAssociated skills: disguise, hom, magical law, psychology, stealth, muggle studies, magical theory, enchanting"
        case "sidekick":
            msg = "The sidekick embodies aspects of the steadfast, rogue, and thrill seeker archetypes. Usually, a younger person who has yet to live up to their full potential, someone who seeks to learn from a mentor type figure, or those content not to be the center of attention. Alternatively, the sidekick wishes to belong, to be the hero but is overshadowed by their peers or mentor. Subordinate sidekicks can at times struggle against their (usually) self-imposed restraints, venturing off on flights of fancy that mostly just get them into trouble. Sidekicks usually possess a strong moral code of duty and responsibility.\nExamples: Ron Weasley, Colling Creevey \nAssociated skills: comc, fast talk, first aid, photography, magizoology, stealth, dodge"
        case "steadfast":
            msg = "Moral righteousness runs thickly in the blood of the steadfast. They protect the weak, put the interests of the others before themselves, and would willingly sacrifice their life for another\'s safety. Whether they follow a clear spiritual or religious path or some internal moral code, they do not stoop to the depths of others, fighting with honor and acting as role models to those around them. Whatever else they fight for, they also fight for justice.\nExamples: Remus Lupin, Molly Weasley. \nAssociated skills: flying (brooms), duelling (both), first aid, hom, magical law, intimidate, persuade, psychology, survival"
        case "swashbuckler":
            msg = "Passionate and idealistic souls who are always looking to rescue damsels in distress. Gallant and heroic, the swashbuckler is action-orientated and fights fairly, disdaining the use of firearms as the tools of cowards. Most likely boastful, noisy, and joyous, even when in the direst of situations. A romantic at heart, a swashbuckler possesses a strong code of honor but is prone to reckless behavior that risks more than just their own life. \nExamples: Gilderoy Lockhart (or rather, the image he presented) \nAssociated skills: arts/crafts (any), duelling (defence), language (other) stealth, flying (brooms), charm, dada, charms"
        case "thrill seeker":
            msg = "Some people are like moths to a flame. For them, the easy life is no life at all, and they must seek out adventure and danger in order to feel alive. The stakes are never high enough for thrill seekers, who are always ready to bet large in order to feel the rush of adrenaline pumping through their veins. Such daredevils are drawn to high-octane sports and activities, and for them, a mountain is a challenge to master. Foolhardy to a fault, they cannot understand why no one else is prepared to take the same risks as they do.\nExamples: Sonic the hedgehog, Lara Croft \nAssociated skills: arts/craft (any), charm, flying (both), fast talk, quidditch, dodge, apparition, dragonology, curse breaking"
        case "two fisted":
            msg = "\"Live fast, die hard\" is the motto of the two-fisted. Such individuals are storehouses of energy, strong, tough, and very capable. Such types are inclined to resolve disputes with their fists rather than words. Usually hard-drinking and hardtalking, they like getting straight to the point and dislike pomp and ceremony. They do not suffer fools gladly. The two-fisted seem to live life in a hurry, quick to anger, contemptuous of authority, and ready to play as dirty as the next guy.\nExamples: Draco Malfoy \nAssociated skills: Flying (brooms), brawling, duelling (offence), intimidate, dada, quidditch"
        case _:
            msg = "This archetype is not currently in the list. Either request Seph to add it or try again with a different archetype. For a list of currently available archetypes, please use !infoarchetype \"info\" "

    return msg


